### ISSUE TITLE
Requirement Analysis.

### ISSUE THREAD

**Issue by ravitejamandapati** [shirosaidev/diskover#23]
Hi Chris,

I have initiated scan on multiple filesystems, which is around 500 to 800TB and in future we are planning to use this tool to scan around 7 to 8PB every 3 months. In this case, can you suggest me the environment requirement. I mean to say, what was the hardware requirement for 8PB scan. Current environment details are mentioned below.

Redis Server : Red Hat Enterprise Linux 7.2 (with 128GB RAM, 12 Core * 2 CPUs)
Elasticsearch : Ubuntu 16.04 ( 3 Node Cluster with 32GB RAM, 8 Core CPU and 1TB Storage for elasticsearch data and log on each node)
BOT Count : 600

Thanks & Regards,
RaviTeja

**Comment by draco2003** [comment]
How did your initial scan go? 
Based on your configuration and the scan timing/storage/cpu stats you should be able to get a rough idea on how much you'd need to scale up in order to scan 8PB. 
There are a lot of variables that only you know about your environment, like speed of the hardware hosting the filesystems you are scanning or the protocol your scanning over (NFS, CIFS, Direct Attached)

**Comment by ravitejamandapati** [comment]
I have initiated scan for 450 to 500 TB of data. I can observe that RAM 128GB almost occupied by redis and scan failing with redis memory issues. (it's all 40G pipe network and storage is NetApp and Isilon)

**Comment by draco2003** [comment]
How do you have redis configured? If it's setup to be an LRU cache it seems you'd just configure redis to have the available amount of memory that your system supports, and then it will age out anything that it needs to?
 
We are just spinning up a cluster to test with, and will a have similar sized dataset so will report back with our findings.

I'll have to look through the code to see how it traverses folders, but you can try turning down the TTL for directory caching in redis to slow the growth. It also might make sense to use a hash of the filepath for the redis key instead of the full string to slow the growth of the redis dataset especially for long filepaths/filenames. 

From a quick look If you aren't passing a -I / --index2 argument than you could comment out the redis setting code and avoid the writes to it (or better yet put the same if statement around it that the get code uses:
Set code that doesn't have the if:
https://github.com/shirosaidev/diskover/blob/master/diskover_worker_bot.py#L216
Get code that has the if:
https://github.com/shirosaidev/diskover/blob/master/diskover_worker_bot.py#L112

**Comment by shirosaidev** [comment]
Hi RaviTeja,
Are you running 600 worker bots all on 1 host, on the rhel server? Is this all on bare metal or vm?
You may see diminishing returns running that many bots using a single diskover.py crawl. Are you running crawls in parallel? You could try running `rqinfo -i 2` during crawl to see how idle the bots are. If they are all busy most of the time that's great :)
-I / --index2 cli arg is used to get meta data from an existing index in ES when the mtimes of directories are the same. This is to reduce amount of stat calls to the disk/network. Mtimes for each directory are stored in Redis for a default of 1 week (setting in diskover.cfg).

**Comment by ravitejamandapati** [comment]
it's bare metal with 2 * 12 care CPU's and 128GB RAM.
from redis point on you, i have not changed anything after instillation. If we required to configure something from redis side, please share with me.
I am running parallel crawls with each mount separate index name.

Please let me know if you required to change any config to perform well or do the crawler more faster.

**Comment by shirosaidev** [comment]
I have written an optimization guide, this may help you to get the best performance when crawling
https://github.com/shirosaidev/diskover/wiki/Optimizing

**Comment by shirosaidev** [comment]
You mentioned the only issue you were having was with Redis memory? Which version of Redis are you running? I've been testing on 4.0.8 and haven't seen any issues yet, but I'm not testing with as big as data set as you are...

**Comment by shirosaidev** [comment]
Also what is the full command you are using to start the crawl? Are you using -a or -b ?

**Comment by ravitejamandapati** [comment]
im using "-a"

**Comment by shirosaidev** [comment]
Are you still having any issues crawling? It might be helpful to install x-pack to look at ES monitoring in Kibana during crawl..  Also this redis monitoring guide might help if you need to see what's going on with Redis
https://scalegrid.io/blog/6-crucial-redis-monitoring-metrics/

**Comment by shirosaidev** [comment]
@ravitejamandapati any more issues with redis and crawling in latest release of rc10? Please try with the latest patches to rc10 up on github and let me know.
