### ISSUE TITLE
The directions for this are awful

### ISSUE THREAD

**Issue by ochompsky** [shirosaidev/diskover#53]
Tons of missing dependancies that aren't even in the document.  Specific versions that aren't listed.  

I'd ask why you don't just make an all-in-one container but it seems like you'd rather sell it.

**Comment by CHBMB** [comment]
Bundling lots of services into one docker container isn't how things are meant to be done.  

As for the dev rather selling it, are you stupid?  It's all opensource, he has a patreon and a paypal link for donations, but why shouldn't people be able to get donations from all their hard work.

Quick look at your github account shows you're a real valuable member of the open source community, thanks for all your contributions..... oh, wait. It's empty.

If you think the directions are bad, then ask for help, and when you figured it all out, submit a PR to improve the docs rather than moaning about the state of things.  

I'm sorry but people like you make me sick, you want to use free and opensource software, then moan about things, all the while, doing nothing to improve things.

I've not used this before, but just got it up and running with this.

Using a custom network called `docker-network`

`docker network create docker-network`

```
docker run -d --name='elasticsearch' \
--net='docker-network' \
-e 'discovery.type'='single-node' \
'elasticsearch:5.6.14' 
```

```
docker run -d --name='redis' \
--net='docker-network' \
-p '6379:6379/tcp' \
'redis'
```

```
docker run -d --name='diskover' \
--net='docker-network' \
-e 'REDIS_HOST'='redis' \
-e 'REDIS_PORT'='6379' \
-e 'ES_HOST'='elasticsearch' \
-e 'ES_PORT'='9200' \
-e 'ES_USER'='elastic' \
-e 'ES_PASS'='changeme' \
-e 'INDEX_NAME'='diskover-' \
-e 'DISKOVER_OPTS'='' \
-e 'WORKER_OPTS'='' \
-e 'RUN_ON_START'='true' \
-e 'USE_CRON'='false' \
-e 'PUID'='99' \
-e 'PGID'='100' \
-p '9181:9181/tcp' \
-p '9999:9999/tcp' \
-p '80:80/tcp' \
-v '/path/to/diskover/config/files/':'/config':'rw' \
-v '/path/to/data/to/analyse/':'/data':'rw' \
'linuxserver/diskover'
```

**Comment by ochompsky** [comment]
Getting it running isn't the problem.  But I suppose basic reading is beyond your comprehension.  

You need to jump off the authors dick.

**Comment by CHBMB** [comment]
Better than yours.... :shrug

**Comment by ochompsky** [comment]
Have nothing is better than the buggy, half baked junk your group puts out

**Comment by CHBMB** [comment]
Don't use them then.  But it's still more than your mammoth contribution to the open source world.

![2019-01-30_20-18](https://user-images.githubusercontent.com/3609888/52009998-3d301380-24cc-11e9-8e07-e2137ba99aac.png)

It's always those that do the least, that moan the most.
