### ISSUE TITLE
Is is possible to use diskover without creating an account with a 3rd party ? 

### ISSUE THREAD

**Issue by domainoverflow** [shirosaidev/diskover#84]
Is it possible to deploy diskover without having to create an account with an unknown entity or issue token myself ? thanks.

**Comment by shirosaidev** [comment]
It's not an unknown entity, it's hosted by the Shirosaidev team who developed diskover.

**Comment by KodeStar** [comment]
@domainoverflow just use the version without the callback, there has been very little added other than the callback itself from what I understand. The linuxserver.io docker uses the non callback version by default if you use docker.

@shirosaidev just because the Shirosaidev team is the one hosting the callback doesn't really make them (you) an unknown entity.

**Comment by domainoverflow** [comment]
Thanks KodeStar !

________________________________

**Comment by domainoverflow** [comment]
> It's not an unknown entity, it's hosted by the Shirosaidev team who developed diskover.

@shirosaidev It's all about having f u l l control and passing compliances in multiple envs. And that doesn't cut it unfortunately.

**Comment by larkwiot** [comment]
Easy patches: https://github.com/larkwiot/diskover
